#[derive(Copy, Clone)]
pub enum RemoteControllerInputEvent {
    HDMISource1,
    HDMISource2,
    HDMISource3,
    InputSourceApple,
    InputSourceTriangle,
    InputSourceWimius,
    LightOff,
    LightOn,
    SoundBassDown,
    SoundBassUp,
    SoundEqualizerReset,
    SoundMute,
    SoundSource,
    SoundTrebleDown,
    SoundTrebleUp,
    SoundVolumeDown,
    SoundVolumeUp,
    TelevisionBack,
    TelevisionDown,
    TelevisionHome,
    TelevisionLeft,
    TelevisionMenu,
    TelevisionPlayPause,
    TelevisionRight,
    TelevisionUp,
    Unknown,
}

impl RemoteControllerInputEvent {
    pub fn from_byte(value: u8) -> RemoteControllerInputEvent {
        match value {
            0x01 => RemoteControllerInputEvent::HDMISource1,
            0x02 => RemoteControllerInputEvent::HDMISource2,
            0x03 => RemoteControllerInputEvent::HDMISource3,
            0x04 => RemoteControllerInputEvent::InputSourceApple,
            0x05 => RemoteControllerInputEvent::InputSourceTriangle,
            0x06 => RemoteControllerInputEvent::InputSourceWimius,
            0x07 => RemoteControllerInputEvent::LightOff,
            0x08 => RemoteControllerInputEvent::LightOn,
            0x09 => RemoteControllerInputEvent::SoundBassDown,
            0x10 => RemoteControllerInputEvent::SoundBassUp,
            0x11 => RemoteControllerInputEvent::SoundEqualizerReset,
            0x12 => RemoteControllerInputEvent::SoundMute,
            0x13 => RemoteControllerInputEvent::SoundSource,
            0x14 => RemoteControllerInputEvent::SoundTrebleDown,
            0x15 => RemoteControllerInputEvent::SoundTrebleUp,
            0x16 => RemoteControllerInputEvent::SoundVolumeDown,
            0x17 => RemoteControllerInputEvent::SoundVolumeUp,
            0x18 => RemoteControllerInputEvent::TelevisionBack,
            0x19 => RemoteControllerInputEvent::TelevisionDown,
            0x20 => RemoteControllerInputEvent::TelevisionHome,
            0x21 => RemoteControllerInputEvent::TelevisionLeft,
            0x22 => RemoteControllerInputEvent::TelevisionMenu,
            0x23 => RemoteControllerInputEvent::TelevisionPlayPause,
            0x24 => RemoteControllerInputEvent::TelevisionRight,
            0x25 => RemoteControllerInputEvent::TelevisionUp,
            _ => RemoteControllerInputEvent::Unknown,
        }
    }
    pub fn to_byte(&self) -> &[u8] {
        match self {
            RemoteControllerInputEvent::HDMISource1 => &[0x01],
            RemoteControllerInputEvent::HDMISource2 => &[0x02],
            RemoteControllerInputEvent::HDMISource3 => &[0x03],
            RemoteControllerInputEvent::InputSourceApple => &[0x04],
            RemoteControllerInputEvent::InputSourceTriangle => &[0x05],
            RemoteControllerInputEvent::InputSourceWimius => &[0x06],
            RemoteControllerInputEvent::LightOff => &[0x07],
            RemoteControllerInputEvent::LightOn => &[0x08],
            RemoteControllerInputEvent::SoundBassDown => &[0x00],
            RemoteControllerInputEvent::SoundBassUp => &[0x10],
            RemoteControllerInputEvent::SoundEqualizerReset => &[0x11],
            RemoteControllerInputEvent::SoundMute => &[0x12],
            RemoteControllerInputEvent::SoundSource => &[0x13],
            RemoteControllerInputEvent::SoundTrebleDown => &[0x14],
            RemoteControllerInputEvent::SoundTrebleUp => &[0x15],
            RemoteControllerInputEvent::SoundVolumeDown => &[0x16],
            RemoteControllerInputEvent::SoundVolumeUp => &[0x17],
            RemoteControllerInputEvent::TelevisionBack => &[0x18],
            RemoteControllerInputEvent::TelevisionDown => &[0x19],
            RemoteControllerInputEvent::TelevisionHome => &[0x20],
            RemoteControllerInputEvent::TelevisionLeft => &[0x21],
            RemoteControllerInputEvent::TelevisionMenu => &[0x22],
            RemoteControllerInputEvent::TelevisionPlayPause => &[0x23],
            RemoteControllerInputEvent::TelevisionRight => &[0x24],
            RemoteControllerInputEvent::TelevisionUp => &[0x25],
            RemoteControllerInputEvent::Unknown => &[0x00],
        }
    }
}